# Generated by Django 5.2.12 on 2026-06-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Captación y Pretratamiento'), ('B', 'Ósmosis Inversa (RO)'), ('C', 'Postratamiento y Almacenamiento'), ('D', 'Energía Solar y SCADA')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='online', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='AQUA-8 Cloud', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('location_name', models.CharField(default='Manaure, La Guajira', max_length=100)),
                ('latitude', models.FloatField(default=11.78)),
                ('longitude', models.FloatField(default=-72.45)),
                ('total_production_liters', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Status',
                'verbose_name_plural': 'System Status',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='aqua8.module')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('tds_in', models.FloatField(blank=True, null=True, verbose_name='TDS Entrada (ppm)')),
                ('tds_out', models.FloatField(blank=True, null=True, verbose_name='TDS Salida (ppm)')),
                ('tank_level', models.FloatField(blank=True, null=True, verbose_name='Nivel Tanque (%)')),
                ('solar_production', models.FloatField(blank=True, null=True, verbose_name='Producción Solar (kW)')),
                ('battery_level', models.FloatField(blank=True, null=True, verbose_name='Batería (%)')),
                ('energy_consumption', models.FloatField(blank=True, null=True, verbose_name='Consumo (kW)')),
                ('scada_status', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='aqua8.module')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
