# Generated by Django 5.2.12 on 2026-06-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('ejecucion', 'En Ejecución'), ('aprobado', 'Aprobado'), ('completado', 'Completado')], default='planificado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_calculo', models.CharField(blank=True, max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorias', to='aqua8.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('jpg', 'Imagen'), ('dwg', 'AutoCAD'), ('zip', 'Comprimido'), ('otro', 'Otro')], default='pdf', max_length=20)),
                ('tamano', models.CharField(blank=True, max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='aqua8.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capitulo_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqua8.capitulomaestro')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='aqua8.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'capitulo_maestro')},
            },
        ),
    ]
