# Generated by Django 5.2.12 on 2026-06-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua8', '0002_capitulomaestro_proyecto_memoriacalculo_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_presupuesto', to='aqua8.proyecto')),
            ],
            options={
                'verbose_name_plural': 'Categorias de Presupuesto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.FloatField(default=1)),
                ('unidad', models.CharField(default='und', max_length=50)),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario_cop', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='aqua8.categoriapresupuesto')),
            ],
            options={
                'verbose_name_plural': 'Partidas presupuestarias',
                'ordering': ['numero'],
            },
        ),
    ]
